### ISSUE TITLE
Where is the bitcoin module?

### ISSUE THREAD

**Issue by vinc456** [ethereum/pyethsaletool#1]
python pyethsaletool.py genwallet testpassword some@emailaddress.com # command line input
`Traceback (most recent call last):
  File "pyethsaletool.py", line 9, in <module>
    from bitcoin import *
ImportError: No module named bitcoin`

Where can I find the bitcoin module?

**Comment by vinc456** [comment]
There appear to be three occurrences/references to the bitcoin module in this repo and the master.zip archive found at https://blog.ethereum.org/2014/07/23/ether-purchase-troubleshooting/ but the module is nowhere to be found.

``` pyethsaletool.py
9:from bitcoin import *
54:# use pybitcointools' internal ecdsa implementation
67:        u = k.sign(bitcoin.bin_txhash(tx))
210:        # uses pybitcointools' 3-source random generator

genesis_block_generator.py
1:import bitcoin as b

test.py
3:from bitcoin import *
```

**Comment by vinc456** [comment]
Perhaps this tool is no longer supported but I am trying to create a wallet to hold/contain the Ether I am mining. If this pyethsaletool is not necessary or there is an alternative then please let me know, thanks.

**Comment by ethers** [comment]
try: `pip install bitcoin`
Source is: https://github.com/vbuterin/pybitcointools

**Comment by vinc456** [comment]
I can now successfully run the pyethsaletool. 
On gitter ethers also mentioned "If you are using Geth to mine, the ether will be stored in one of your Geth accounts"

Thanks for your help!
